# Ores

- name: IronOre
  reactivationRate: 14000
  isToolRequired: true
  toolCategory: Pickaxe
  gloryGiven: 10
  expGiven: 10
  gatherTime: 5000
  gatheringTask: IronOre
  itemName: IronOre

- name: DungiumOre
  reactivationRate: 30000
  isToolRequired: true
  toolCategory: Pickaxe
  gloryGiven: 15
  expGiven: 25
  gatherTime: 10000
  gatheringTask: DungiumOre
  itemName: DungiumOre

- name: AgoniteOre
  reactivationRate: 45000
  isToolRequired: true
  toolCategory: Pickaxe
  gloryGiven: 20
  expGiven: 40
  gatherTime: 15000
  gatheringTask: AgoniteOre
  itemName: AgoniteOre

- name: NoctisOre
  reactivationRate: 60000
  isToolRequired: true
  toolCategory: Pickaxe
  gloryGiven: 30
  expGiven: 60
  gatherTime: 20000
  gatheringTask: NoctisOre
  itemName: NoctisOre

# Trees

- name: PineTree
  reactivationRate: 20000
  toolCategory: Hatchet
  gloryGiven: 6
  expGiven: 5
  gatherTime: 5000
  gatheringTask: PineLogs
  itemName: PineLogs

- name: WillowTree
  reactivationRate: 30000
  toolCategory: Hatchet
  gloryGiven: 15
  expGiven: 25
  gatherTime: 10000
  gatheringTask: WillowLogs
  itemName: WillowLogs

- name: OakTree
  reactivationRate: 40000
  toolCategory: Hatchet
  gloryGiven: 20
  expGiven: 40
  gatherTime: 15000
  gatheringTask: OakLogs
  itemName: OakLogs

# Mushrooms

- name: BlueMushroom
  reactivationRate: 20000
  toolCategory: Sickle
  gloryGiven: 10
  expGiven: 10
  gatherTime: 4000
  gatheringTask: Bluecaps
  itemName: Bluecap

- name: FrostMushroom
  reactivationRate: 40000
  toolCategory: Sickle
  gloryGiven: 40
  expGiven: 40
  gatherTime: 8000
  gatheringTask: Frostcaps
  itemName: Frostcap

- name: GreenMushroom
  reactivationRate: 20000
  toolCategory: Sickle
  gloryGiven: 10
  expGiven: 10
  gatherTime: 4000
  gatheringTask: Greencaps
  itemName: Greencap

- name: RedMushroom
  reactivationRate: 20000
  toolCategory: Sickle
  gloryGiven: 10
  expGiven: 10
  gatherTime: 4000
  gatheringTask: Redcaps
  itemName: Redcap

# Other

- name: CottonPlant
  reactivationRate: 8000
  gloryGiven: 4
  expGiven: 10
  gatherTime: 1000
  gatheringTask: Cotton
  itemName: Cotton