
# Everything, for nothing.
- name: Omni
  stock: []

- name: Ruler
  stock: []

- name: Priest
  stock:
  - itemName: HealthPotion
    unitPrice: 250
  - itemName: WardSpellScroll
    unitPrice: 200
  - itemName: CleanseSpellScroll
    unitPrice: 120

# Basic gathering tools
- name: Tools
  stock:
    - itemName: IronHatchet
      unitPrice: 150
    - itemName: IronPickaxe
      unitPrice: 150
    - itemName: DungiumHatchet
      unitPrice: 800
    - itemName: DungiumPickaxe
      unitPrice: 800

# Melee combat gear
- name: Melee
  stock:
    - itemName: IronDagger
      unitPrice: 200
    - itemName: IronSword
      unitPrice: 300
    - itemName: IronHammer
      unitPrice: 350
    - itemName: DungiumSword
      unitPrice: 850
    - itemName: IronArmour
      unitPrice: 800

# Ranged combat gear
- name: Ranged
  stock:
    - itemName: PineBow
      unitPrice: 300
    - itemName: WillowBow
      unitPrice: 800
    - itemName: IronArrows
      unitPrice: 5
    - itemName: DungiumArrows
      unitPrice: 20
    - itemName: Shuriken
      unitPrice: 7
    - itemName: Cloak
      unitPrice: 700

# Magic combat gear
- name: Magic
  stock:
    - itemName: HealAreaSpellScroll
      unitPrice: 200
    - itemName: PacifySpellScroll
      unitPrice: 200
    - itemName: WindStaff
      unitPrice: 300
    - itemName: FireStaff
      unitPrice: 500
    - itemName: PlainRobe
      unitPrice: 400
    - itemName: MageRobe
      unitPrice: 650

# Inn/bar
- name: Inn
  stock:
    - itemName: HealthPotion
      unitPrice: 250
    - itemName: EnergyPotion
      unitPrice: 150

# PvP arena
- name: Arena
  stock:
    - itemName: FighterKey
      unitPrice: 1000

# Raw materials
- name: Materials
  stock:
    - itemName: IronBar
      unitPrice: 200
    - itemName: PineLogs
      unitPrice: 140
    - itemName: Feathers
      unitPrice: 100
    - itemName: Fabric
      unitPrice: 200
    - itemName: Cotton
      unitPrice: 120

# Dwarf weapons
- name: DwarfWeapons
  stock:
    - itemName: IronPickaxe
      unitPrice: 400
    - itemName: IronArrows
      unitPrice: 10
    - itemName: IronSword
      unitPrice: 600
    - itemName: IronHammer
      unitPrice: 650
    - itemName: IronArmour
      unitPrice: 1500
    - itemName: DungiumSword
      unitPrice: 1200
    - itemName: DungiumHammer
      unitPrice: 1200
